### ISSUE TITLE
播放状态监听问题

### ISSUE THREAD

**Issue by bingdu0** [CarGuo/GSYVideoPlayer#2874]
```
GSYVideoOptionBuilder gsyVideoOption = new GSYVideoOptionBuilder().setVideoAllCallBack(new GSYSampleCallBack(){
            @Override
            public void onClickResume(String url, Object... objects) {
                super.onClickResume(url, objects);
            }

            @Override
            public void onAutoComplete(String url, Object... objects) {
                super.onAutoComplete(url, objects);
            }
        });

```

怎么监听播放的暂停 播放状态，这个onClickResume监听是不是只有点击开始暂停按钮的时候 才会回掉？我怎么实时的监听播放状态。如果不重写setStateAndUi（），因为我是Activity 的 ui 布局中的按钮执行的onVideoResume 或者onVideoPause。我要是重写那个方法是不是要自己写一个接口回掉。让Activity 中的ui来监听？还有一个问题 就是seekbar 也是在Activity的ui布局中 自己实现的，播放器有什么方法 更新外部的seekbar？

**Comment by CarGuo** [comment]
GSYVideoProgressListener 可以处理外部 seekbar

内部你可以继承后在重载 setStateAndUi 用于监听

**Comment by wangrunxiang** [comment]
我也是在StandardGSYVideoPlayer的子类中复写onVideoResume不回调，我也尝试了setStateAndUi这个方法，这个方法有个坑，点击播放按钮的时候，setStateAndUi会回调多次，一次是clickStartIcon这个方法回调，其他地方也会回调，所以我计划用开始播放和暂停播放的时间差计算实际播放时间不可靠

**Comment by wangrunxiang** [comment]
@CarGuo

**Comment by ff-frida** [comment]
> 我也是在StandardGSYVideoPlayer的子类中复写onVideoResume不回调，我也尝试了setStateAndUi这个方法，这个方法有个坑，点击播放按钮的时候，setStateAndUi会回调多次，一次是clickStartIcon这个方法回调，其他地方也会回调，所以我计划用开始播放和暂停播放的时间差计算实际播放时间不可靠

我也遇到这样问题，我需要统计视频播放的时间

**Comment by CarGuo** [comment]
@wangrunxiang 如果是你这种情况，建议在 PlayerManager 层面自己做回掉，集成你要的 PlayerManager ，然后在 pause 和 start 方法重载后自己做个回掉判断

**Comment by NewDirection** [comment]
> 我也是在StandardGSYVideoPlayer的子类中复写onVideoResume不回调，我也尝试了setStateAndUi这个方法，这个方法有个坑，点击播放按钮的时候，setStateAndUi会回调多次，一次是clickStartIcon这个方法回调，其他地方也会回调，所以我计划用开始播放和暂停播放的时间差计算实际播放时间不可靠

同问，解决了？

**Comment by wangrunxiang** [comment]
@NewDirection 解决了，是用的作者最后的回复的方式解决的

**Comment by NewDirection** [comment]
可以加下QQ,讨论一下？&nbsp; 934460544




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月19日(星期四) 下午5:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CarGuo/GSYVideoPlayer] 播放状态监听问题 (#2874)





 
@NewDirection 解决了，是用的作者最后的回复的方式解决的
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
